name: Caliper Test
version: "2.0.0"
caliper:
  blockchain: fabric
channels:
  - channelName: mychannel
    contracts:
      - id: basic
organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/workspaces/fabric_certificate_MT/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/REPLACE_WITH_ACTUAL_KEY_FILE'
          clientSignedCert:
            path: '/workspaces/fabric_certificate_MT/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: 'networks/connection-org1.yaml'
      discover: false
